### ISSUE TITLE
BUG Store<T> types missmatch

### ISSUE THREAD

**Issue by bl9l** [ng-state/store#2]
Hi.

In the `update` method in `Store<T>` the argument for callback has to be `List` but it is `IndexedCursor`.

[The file](https://stackblitz.com/edit/ng-state-sample-app?file=src%2Fapp%2Fimmutable-app%2Factions%2Ftodos.actions.ts)

![image](https://user-images.githubusercontent.com/46722973/69325542-267dc780-0c6c-11ea-9989-7ab6f4ca10f7.png)

**Comment by bl9l** [comment]
I found that `List` is just an interface but still, signatures differs

**Comment by vytautas-pranskunas-** [comment]
Actually it is not a bug. It is List however under the hood it uses ImmutableCursor which creates indexed cursor to original source by provided path. However your state (todos) is list of todo items.
Anyway please consider switching to https://www.npmjs.com/package/@ng-state/store
and I would recommend ImmerDataStrategy (immerjs) because ImmutableJs 4.0.0 relase stucked in place for a year or so.

**Comment by vytautas-pranskunas-** [comment]
It will be same when you use immer. in update you will see not actual object but proxy object which takes care about maipulating original source
